### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by dani-garcia** [BlackDex/favicon_download#1]
I didn't look very deeply into this, but I have a couple of comments:

1- I see this repeated a couple of times:
```rust
let parsed_url = Url::parse(&ssldomain.to_string())?;
let mut url = format!("{}://{}", parsed_url.scheme(), parsed_url.host().unwrap()); 
```

What is it supposed to be doing, just validating that the domain is valid? Because the way I see it, `ssldomain` would be equal to `url`.

2- This whole block:
```rust
if let Ok(mut content) = resp {
        if debug == "true" {
            println!("content: {:#?}", content);
        }
        body = content.text().unwrap();
        let parsed_url = Url::parse(&content.url().to_string())?;
        url = format!("{}://{}", parsed_url.scheme(), parsed_url.host().unwrap());
    } else {
        let resp = client.get(&httpdomain).send();
        if let Ok(mut content) = resp {
            if debug == "true" {
                println!("content: {:#?}", content);
            }
            body = content.text().unwrap();
            let parsed_url = Url::parse(&content.url().to_string())?;
            url = format!("{}://{}", parsed_url.scheme(), parsed_url.host().unwrap());
        }
    }
```

can probably be simplified to something like:
```rust
    let resp = client.get(&ssldomain).send().or_else(|_| client.get(&httpdomain).send());
    if let Ok(mut content) = resp {
        if debug == "true" {
            println!("content: {:#?}", content);
        }
        body = content.text().unwrap();
        let parsed_url = &content.url();
        url = format!("{}://{}", parsed_url.scheme(), parsed_url.host().unwrap());
    }
```
We are basically chaining both operations, if the first succeeds, we get that result, otherwise we get whatever the second one returns.
There is also no need to parse the URL here, we already have  a URL.

Edit: You might want to do this too:
```rust
    let resp = client.get(&ssldomain).send().or_else(|_| client.get(&httpdomain).send())?;
    if debug == "true" {
            println!("content: {:#?}", content);
    }
    body = content.text().unwrap();
    let parsed_url = &content.url();
    url = format!("{}://{}", parsed_url.scheme(), parsed_url.host().unwrap());
```

That way if both fail we return an error and we don't have to check if the response is OK.

**Comment by mprasil** [comment]
The check for extension in `favicon_href` could be a bit more concise. You don't have to do `something() == true` if the function already returns `bool`. Also no need to do `== false`, you can just negate the expression with `!`.  Here I've also flipped the whole logic and used `or` instead of `and` logic: 

```
if favicon_href.is_empty() || 
        !(favicon_href.ends_with(".ico") ||
          favicon_href.ends_with(".png") ||
          favicon_href.ends_with(".jpg") ||
          favicon_href.ends_with(".jpeg"))
    {
```

I still feel like something more appropriate (possibly some loop over extensions would be better here as this is already quite repetitive and it doesn't yet handle cases where the extension is uppercase for example.

**Comment by dani-garcia** [comment]
In fact, ends_with works with an array:
https://doc.rust-lang.org/std/primitive.slice.html#method.ends_with

Edit: Woops, ignore that, that's for slices

Edit2: A possible alternative is
```rust
const VALID_EXT: [&'static str; 4] = [".png", ".ico", ".jpg", ".jpeg"];
    
fn is_valid_ext(url: &str) -> bool {
    VALID_EXT.iter().any(|e| url.ends_with(e)) 
}
```

**Comment by dani-garcia** [comment]
Another two things:

First, if you want to avoid the uninitialize body completely, you can use ? to avoid the if and then initialize the body at first use:

```rust
    let ssldomain = format!("https://{}", rawdomain);
    let httpdomain = format!("http://{}", rawdomain);

    let resp = client.get(&ssldomain).send().or_else(|_| client.get(&httpdomain).send())?;
    if debug == "true" {
        println!("content: {:#?}", content);
    }
    let body = content.text().unwrap();
    let url = format!("{}://{}", content.url().scheme(), content.url().host().unwrap());
``` 

You could also use Options instad of assigning default values, which are unused:
```rust
for favicon in favicons {
        let favicon_sizes = favicon.get("sizes");
        let mut favicon_href = match favicon.get("href") {
            Some(href) => href,
            None => continue, // If no value, skip
        };

        // Only continue if href is not empty
        let favicon_priority;
        if favicon_href.is_empty() == true || (
            favicon_href.ends_with(".ico") == false
            && favicon_href.ends_with(".png") == false
            && favicon_href.ends_with(".jpg") == false
            && favicon_href.ends_with(".jpeg") == false) {
            continue;
        }

        // Check if there is a dimension set
        if let Some(favicon_sizes) = favicon_sizes {
```

And lastly, I would personally extract the code to calculate priorities and the code that adds the scheme and or host to separate functions.

I got to do some testing, and it seems to work correctly for the sites I tried, nice work @BlackDex!

**Comment by dani-garcia** [comment]
This is starting to look better!

A couple of things, first you have two unused crates in the toml, it seems (select and html5ever).

I quite like the regex solution to the extension, nice work there.

We should try to make sure to not return empty values, which are quite useless, and basically equivalent to an error for most cases:
- If both requests fail, we'll continue with `body = ""`, which means empty icon list and empty result at the end. To solve this I would recommend to use the ? trick I mentioned in the last comment, or at least to add an else to the `if let Ok` that returns an error. With this, we can also remove the `body.is_empty` check.
- At the end, if we can't get `Some(icon)` from `iconlist.first` I would also return an error in an `else` block.

Note that you might not easily be able to return a custom error from your crate, but once you add the code to bitwarden_rs, you can use `err!("No icons found or whatever")`

- Also, and this is mostly style, `if-else` blocks can return values, so you can do something like this:
```rust
fn get_icon_priority(href: &str, sizes: &str) -> u8 {
    // Previous stuff ignored
    
    if width == 32 {
       1
    } else if width == 64 {
        2
    } else if width >= 24 && width <= 128 {
        3
    } else if width == 16 {
        4
    } else {
        100
    }
}
```

This allows you to avoid repeating `priority = X` all over the place.

And with that, I think you can create a PR already, just rename your `get_icon_url_extra` function to `get_icon_url` and copy the code in the `icons.rs` file.

**Comment by BlackDex** [comment]
Well i think i have it all nice and clean now.
Thanks for all the tips :+1: 

The result will always have an URL since it will at least return the given domain with /favicon.ico attached. I tried to remove the Result<> as a return value and make it just a String, but that isn't possible. And creating an intermediate function just to return a String instead of a Result<(String)> is too much i think.

I will try and add this code to bitwarden_rs and see what it does :)
